### ISSUE TITLE
Update Help to version 2.0.0

### ISSUE THREAD

**Issue by arnaldmarcer** [rtdeb/GeoPick#101]
@tucotuco @ArthurChapman @aescobarr What do you think of these two texts for the help page. The first one is just an update of what was there, and the second one is new.

------- 

**Getting georeference results**
Use these three buttons to validate the georeference data and export data to the clipboard in a spreadsheet-friendly tab-delimited format.

Once you have filled in the Locality, Georeferenced by, and, optionally, the Georeference remarks in the Info box, you need to click on the Validate button to confirm the georeference data. Then you can export it. You just need to click on the With headers or Without headers button and all data will be copied to the clipboard. If you choose With headers, the headers (field names) of each georeference field will also be copied. On the contrary, if you choose Without headers, only the data will be copied. You may be georeferencing more than one location and this will serve you to copy the headers only for the first one. From the second on, you will be able to paste them in each following row of a spreadsheet without repeating column names.

NOTE: Some spreadsheets limit the number of characters per cell (e.g., Microsoft Excel: 32 767, Google Sheets: 50 000). Since some geometries can get quite complicated and exceed 32 767 characters, specially those imported from Nominatim, GeoPick let's the user decide whether to copy or not the WKT representation of the geometry when copying data.

------- 

**Sharing georeferences**
You can use GeoPick to share your georeferences with colleagues.

GeoPick will assign a unique ID to each georeference and provide you with a link which you can share with your colleagues. The link will take the form of https://geopick.gbif.org/?locationid=<geopick_id>. This allows to collaborate with your colleagues by allowing double-check of the quality of georeferences and by being able to share georeferences. However, in the case of sharing, you should copy the data into your database/spreadsheet since GeoPick can not guarantee the long-term survival of the georeference data.

GeoPick also allows you to show a simple point-radius geometry to a colleague by using a parameterized URL in the form of
_https://geopick.gbif.org/?lat=<latitutde in decimal degrees>&lon=<longitude in decimal degrees>&unc=<coordinate uncertainty in meters>_
When navigating to such a URL with a browser GeoPick will show the point-radius geometry.

-------

**Comment by tucotuco** [comment]
The first text looks great. For the second one I have only these minor
suggestions:

"GeoPick will assign a unique ID to each georeference and provide you with
a link, which you can share with your colleagues.

In place of

"GeoPick will assign a unique ID to each georeference and provide you with
a link which you can share with your colleagues.

That's just an addition of a comma.

"This promotes collaboration with colleagues by allowing the quality of
georeferences to be double-checked and by allowing georefetences to be
shared."

In place of

"This allows to collaborate with your colleagues by allowing double-check
of the quality of georeferences and by being able to share georeferences."

'Even so, be sure to copy your georefetence data into your
database/spreadsheet because its long-term storage in GeoPick can not be
guaranteed."

in place of

"However, in the case of sharing, you should copy the data into your
database/spreadsheet since GeoPick can not guarantee the long-term survival
of the georeference data."

**Comment by arnaldmarcer** [comment]
Thanks @tucotuco, changes applied. Will be visible later on.

**Comment by arnaldmarcer** [comment]
Done

**Comment by aescobarr** [comment]
Just a small typo, in the first document where it says

"Nominatim, GeoPick let's the user decide"

I think it should be 

"Nominatim, GeoPick **lets** the user decide"

**Comment by arnaldmarcer** [comment]
Thanks @aescobarr, corrected
