### ISSUE TITLE
Question about the API response

### ISSUE THREAD

**Issue by samleeflang** [rtdeb/GeoPick#93]
Congratulations on this very nice tool and the presentation in TDWG 2023!
We are very interested to implement a georeference service based on this as Machine Annotation Service in DiSSCo.
The first version would be to georeference Specimen which do have a locality but are missing a georeference.
At the moment we just use the nominatim API but the added value GeoPick provides is very clear.
Just to verify, we would first call nominatim API and then use that result to call the GeoPick API?

My question is about the API response from GeoPick.
I noticed that the response is a single String which contains the JSON.
What is the reason that it returns a String instead of a JSON response?
We could probably parse the string back to JSON, but it would be easier if it was a JSON response.

Additionally, I would like to ask if it is ok to experiment with the public GeoPick API (low volume)?
If we are going to use it large-scale it would be better to set up our own GeoPick server as you describe in the documentation.
Have or do you consider containerizing the tool and providing this as a public image?

Thanks in advance

**Comment by arnaldmarcer** [comment]
@samleeflang , thank you for your interest. You are right about the return of the API. It was not thought to be queried independently but we are aware it needs to be redesigned. Let us think a little about the points you raised and I will get back to you next week. 
Cheers

**Comment by arnaldmarcer** [comment]
@samleeflang 

**Just to verify, we would first call nominatim API and then use that result to call the GeoPick API?**
Yes, that would be the case. However, as of now, in the case that Nominatim returns us multiple polygons we convert them to a single MultiPolygon before sending it to the GEoPick’s API.

**What is the reason that it returns a String instead of a JSON response?
We could probably parse the string back to JSON, but it would be easier if it was a JSON response.**
You are right. Our API is currently implemented using the plumber R package, and we had some problems that we solved by doing it this way. However, our intention is to change it and we will. For the moment, you may have to do the conversion. I can’t say when we will have it changed but we will do it. I’ll let you know.

**Additionally, I would like to ask if it is ok to experiment with the public GeoPick API (low volume)?
If we are going to use it large-scale it would be better to set up our own GeoPick server as you describe in the documentation.**
Please use this URL for experimenting: https://nhc.creaf.cat/geopick. It is an exact copy of that at GBIF. I'll send you the authorization code by email.

**Have or do you consider containerizing the tool and providing this as a public image?**
Yes, we have. We will do it.
