### ISSUE TITLE
Revisit centroid and uncertainty from URL

### ISSUE THREAD

**Issue by arnaldmarcer** [rtdeb/GeoPick#96]
A suggestion by Joaquim Santos was to be able to send a link to someone so that a centroid and uncertaity can be shared and seen on top of a map. He mentioned the tool maps.ie which does this. The idea is to be able to share with another person the view of a georeferenced locality. In maps.ie they solve it by building a url like:

https://www.maps.ie/draw-radius-circle-map/?lat=40.954298290822635&lng=-8.230133056640627&radius=501.3819989059577

which may be pretty easy to implement. We could add a final column in the exported data with the url.

What do you think @tucotuco and @ArthurChapman and @aescobarr?

**Comment by aescobarr** [comment]
If the only parameters that we want to share are lat/lng and radius like the above example, it's pretty straightforward. If what you want to share is a full GeoPick georeferencing info set, that's another story because the involved parameters (specially the geometry) don't fit in a url.

A possible method for achieving this would be to storing all the GeoPick params (including geometry) in the API database and assigning a randomly generated short(ish) key to the information set. For instance - xVfxL. Then you could send the link, which would be relatively small and manageable (i.e https://geopick.gbif.org/share=xVfxL). 
When the person receiving the link opened this, the associated info would be retrieved from the database using the key and then rendered on screen.

**Comment by tucotuco** [comment]
Being able to see what someone else is seeing is extremely useful. In that
respect Agusti's suggestion is very good. I wonder only about any issues
with persistence of the URL and its interpretation in an application that
might change over time.

**Comment by ArthurChapman** [comment]
I agree with @tucotuco. I see less advantage of sending just the circle as done in the other app as it doesn't reflect what the GeoPick app is attempting to do.  Augusti's suggestion would seem to be an ideal solution. What about a third (simple) option with a third button (Share) as suggest by @arnaldmarcer that would send a screen shot of the GeoPick page (showing the circle, polygon, etc. and the right-hand panel) and the text that is Copied to the Clipboard (with header)

**Comment by tucotuco** [comment]
I have been thinking a bit more about this. Right now if someone has the WKT, they can paste it in GeoPick and reproduce the view including the full georeference. This is already agnostic of any GeoPick versioning. There is a problem when the WKT is too big, but that will always be the case. 
To cover the point-radius case, what if there was an equivalent to the WKT button that would allow someone to enter the lat/lng/uncertainty combination? It could support three numbers whose values are separated by spaces or commas or tabs.

**Comment by arnaldmarcer** [comment]
@tucotuco this is already possible. Just click on the keyboard icon.

**Comment by tucotuco** [comment]
Not exactly, no? You can't make a single copy paste, right?

**Comment by arnaldmarcer** [comment]
Yeah, I see, ok. But adding a simple extra textbox there which allows the "lon,lat,unc" format would suffice. No need to add still another control to the UI.

I think though we could, in a first phase since they are easy to implement and solve some use cases:
1. Enable copy/paste as you suggest
2. Enable URL copy/paste as Joaquim suggested
accept a URL as Joaquim suggested.

And, on a second phase (2024) since that could be pretty powerful/neat to do:
3. Implement what Agustí suggested but including the whole georeferencing (WKT) also, as you said. For this we'll need to devise a way to store georeferences. This would also add the nice thing of growing a database of georeferenced sites. This makes me think it would be nice to keep the georeferences, with WKT, along with the verbatim localities to make the database better for potential future uses.

**Comment by tucotuco** [comment]
> Yeah, I see, ok. But adding a simple extra textbox there which allows the "lon,lat,unc" format would suffice. No need to add still another control to the UI.

Exactly.

> I think though we could, in a first phase since they are easy to implement and solve some use cases:
> 
> 1. Enable copy/paste as you suggest
> 2. Enable URL copy/paste as Joaquim suggested

This seems to me to be unneeded development. The same effect can be achieved with a click and paste in GeoPick (if the point-radius lat/lng/unc paste is enabled). I am not opposed to convenience, but I had understood the guiding principle of the application to be as streamlined as possible to achieve a desired set of objectives. If I am wrong about that, that's fine, but otherwise I see the URL solution as not adding a new capability (at least not enabling sharing and viewing a georeference from someone else in GeoPick, which it can do). Not only it is it not adding a new capability, it is significantly adding to the requirements of the application. 
I have no problem if this perspective does not align with the direction you hope to go. I just wanted to put it out there.

> And, on a second phase (2024) since that could be pretty powerful/neat to do:
> 
> 3. Implement what Agustí suggested but including the whole georeferencing (WKT) also, as you said. For this we'll need to devise a way to store georeferences. This would also add the nice thing of growing a database of georeferenced sites. This makes me think it would be nice to keep the georeferences, with WKT, along with the verbatim localities to make the database better for potential future uses.

GeoPick is able to do "Feature only" georeferences. A GeoPick gazetteer could be made in which "Feature only" georeferences were stored from GeoPick. This would help with more than one use case. BioGeomancer was capable of this - making a user-contributed gazetteer of named places, and there were at least three very useful cases for this. One case was for named places that were never going to be found in traditional gazetteers, such as study plots or camp sites or other such esoteric places. The second case was for the storage of georeferences for feature only locations that have only coordinates without any extent. The third case was for storage of alternative interpretations of feature only locations for which no satisfactory interpretation could be found in other linked gazetteer sources. 

As we get into expanded capabilities it is worth thinking about effort versus impact. When we investigated prevalence of locality types in the past, feature only locations constituted 51% of distinct locality descriptions found. Georeferences for these are more or less trivial aside from boundary subjectivity. The next most prominent locality type is offset at a heading from a feature, with 17.6%. To be able to georeference such locations automatically once the feature is bounded would be a non-trivial addition. This would be a very type of new capability very different from the back-end gazetteer one. It would put us on the road to automated georeferences. That is admittedly a long road to travel to be comprehensive, but there is a lot of impact in enabling a few locality types.

**Comment by arnaldmarcer** [comment]
I agree with you, however the second case you mention, expanded capabilities, it is currently not in our list of doable things. Nevertheless, at some point we might try to tackle the most simple case, e.g. an offset and a heading, to explore what it involves.

With respect to keeping a gazetteer of feature-only places, the reason stems from the fact that if we do the url-sharing that we talked about, the stored gazetteer is a given. The only thing is that we would need the users to type or copy/paste the text of the locality description into a new textbox, and that is an additional item of work for users who are busy or reluctant to this kind of work. Anyway, we would need to talk to Matt to see if this is doable on their part. I think it shouldn't be much of an issue because the gazetteer could be kept in a single sqlite file and I do not expect it to grow to a size which could not be dealt with.

**Comment by arnaldmarcer** [comment]
Continue on #61

**Comment by arnaldmarcer** [comment]
This issue continues on #61
