### ISSUE TITLE
Check version 2.0.0 before production deployment

### ISSUE THREAD

**Issue by arnaldmarcer** [rtdeb/GeoPick#98]
Please check new version 2.0.0 with sharing capabilities at https://nhc.creaf.cat/geopick

**Comment by ArthurChapman** [comment]
Great work guys 

A couple of observations/comments

1. I see **georeferencedDate** is added in the cut/paste but wonder if it should also be on the form page near Georeferenced By.  Of course, This may add additional clutter which wouldn't be good. I notice that the date/time becomes part of the LocalityID . I suggest this because one may create a georeference for a locality, but then create another at a later date and inadvertently give it the same name. Not sure about this and the best way to handle.
2. Will it be possible that the import from Postgres be by name or searchable by name?  Not sure how this could be done. I know it may be difficult, and possible something for consideration further down the line, but when one does the Nominatum search (e.g. for Ballan and I get two options: "Ballan, Shire of Moorabool, Victoria, Australia" and "Ballan, Shire of Moorabool, 3342, Victoria, Australia" if it could also add an option "Ballan (Arthur Chapman, personal, 2004-01-31)" or something similar.
3. I notice the LocalityID includes the date in local time (20240201074704) but the georeferencedDate is in UTC (2024-01-31T20:47:06.084Z) in the same record - perhaps these should both be in UTC format.
4. The import from PostGres worked well when I tried it. 
5. Using the coordinate import https://nhc.creaf.cat/geopick?long=2&lat=42&unc=10000 - it didn't work. It didn't place a pin or uncertainty circle.  
6. Using the coordinate import - it should probably be in lat/long rather than long/lat for consistency (the order we use elsewhere)

Again- great work and worthwhile additions. I like it.

**Comment by arnaldmarcer** [comment]
@ArthurChapman thanks for your comments
1.- Yes, I think the Info box should be complete with all the Darwin Core fields but this requires quite an overhaul to make it all fit in there and we do not want to do it lightly. Let's leave this for a later minor version. With respect to the locationID, it just needs to be thought as a simple id with no interpretation purposes. We do use the date and time to generate it plus a final random number between 000 and 999.
2.- That could be pondered on. I also do not see what would the best strategy be and how doable it is. Let's keep it as a possibility down the line. 
3.- Although I just said in point 1 that the id needs to be interpreted just as a string id, I think we can do this.
4.- Perfect
5.- That is my fault. There is a typo in the link I gave. 'long' should be 'lon', that is https://nhc.creaf.cat/geopick?lon=2&lat=42&unc=10000 @tucotuco please also note this.
6.- It doesn't matter the order in the parameters in the url. It can lat,lon,unc without problem, even unc,lon,lat

**Comment by ArthurChapman** [comment]
Thanks @arnaldmarcer 5) works now. We will need a way of being able to input values.
